### ISSUE TITLE
Document the process for creating the dot map

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses.io#48]
I'd love to automate the process of generating the dot map data. We have solid support from AWS to make this happen, we just need whoever is generating the map now to document the process so it can be automated.

Is that you, @kelvinabrokwa?

**Comment by kelvinabrokwa** [comment]
@iandees yes. The script for generating it and the style is [in this repo](https://github.com/openaddresses/openaddresses.io/blob/gh-pages/_src) and I can send you a personal message with the MapBox account creds that I created to host the data. I just fire up and EC2 and generate it there since its so much data. Does OA have EC2s? 

Also note that [the script](https://github.com/openaddresses/openaddresses.io/blob/gh-pages/_src/make_mbtiles.sh) that generates the map using tippecanoe currently fails on uploading to Mapbox.com so you have to `scp` the .mbtiles file to your local machine and then you can upload it using a browser. Hopefully I can fix that pretty soon.

**Comment by iandees** [comment]
Awesome, thanks!

**Comment by migurski** [comment]
The dot map is now being updated on a regular basis; documentation is here: https://github.com/openaddresses/machine/blob/master/docs/components.md#dotmap
